services:
  main:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MODEL_NAME=insurance
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
                